---
debug: false
install_method: source
ceph_mons:
    - 192.168.122.91
haproxy_keepalived_external_vip_cidr: "192.168.122.99/32"
haproxy_keepalived_internal_vip_cidr: "192.168.24.99/32"
haproxy_keepalived_external_interface: enp1s0
haproxy_keepalived_internal_interface: br-mgmt


generate_fsid: false
fsid: b9db2ddd-41c0-4a67-8478-b40ee5b2de3c  # Replace with your generated UUID

monitor_address_block: "{{ cidr_networks.container }}"
public_network: "{{ cidr_networks.container }}"
cluster_network: "{{ cidr_networks.storage }}"

journal_size: 10240 # size in MB
openstack_config: true

cinder_ceph_client: cinder
glance_ceph_client: glance
glance_default_store: rbd
glance_rbd_store_pool: images
nova_libvirt_images_rbd_pool: vms

cephx: true
#ceph_keyrings_dir: /etc/openstack_deploy/ceph-keyrings


cinder_backends:
  rbd:
    volume_driver: cinder.volume.drivers.rbd.RBDDriver
    rbd_pool: volumes
    rbd_ceph_conf: /etc/ceph/ceph.conf
    rbd_store_chunk_size: 8
    volume_backend_name: rbd
    rbd_user: "{{ cinder_ceph_client }}"
    rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
    report_discard_supported: true
