---                                 
cidr_networks:                
  container: 192.168.24.0/24        
  tunnel: 172.29.240.0/24     
  storage: 172.29.244.0/24          
used_ips:                           
  - "192.168.24.1,192.168.24.100"
  - "192.168.122.1,192.168.122.100"
  - "172.29.240.1,172.29.240.100"    
  - "172.29.244.1,172.29.244.100"    
global_overrides:                                 
  # The internal and external VIP should be different IPs, however they
  # do not need to be on separate networks.
  external_lb_vip_address: 192.168.122.99
  internal_lb_vip_address: 192.168.24.99
  management_bridge: "br-mgmt"
  provider_networks:
    - network:                       
        container_bridge: "br-mgmt"               
        container_type: "veth"        
        container_interface: "eth1"
        ip_from_q: "container"     
        type: "raw"         
        group_binds: 
          - all_containers
          - hosts     
        is_container_address: true                
    - network:           
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"   
        type: "vxlan"               
        range: "1:1000"             
        net_name: "vxlan"
        group_binds:        
          - neutron_linuxbridge_agent
    - network:                       
        container_bridge: "br-vlan"               
        container_type: "veth"                                                                      
        container_interface: "eth12"
        host_bind_override: "br-vlan"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
    - network:
        container_bridge: "br-ex"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "enp2s0"
        type: "flat"
        net_name: "physnet1"
        group_binds:
          - neutron_linuxbridge_agent

shared-infra_hosts:  
  infra0:                   
    ip: 192.168.24.35
  infra1:                            
    ip: 192.168.24.69
  infra2:            
    ip: 192.168.24.65
                                                  
repo-infra_hosts:    
  infra0:            
    ip: 192.168.24.35
  infra1:             
    ip: 192.168.24.69
  infra2:            
    ip: 192.168.24.65
                                                  
haproxy_hosts:        
  infra0:            
    ip: 192.168.24.35
  infra1:            
    ip: 192.168.24.69
  infra2:            
    ip: 192.168.24.65
identity_hosts:                                                                                     
  infra0:            
    ip: 192.168.24.35
  infra1:  
    ip: 192.168.24.69
  infra2:                                                                                           
    ip: 192.168.24.65
storage-infra_hosts:
  infra0:
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
image_hosts:
  infra0:
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
placement-infra_hosts:
  infra0:
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
compute-infra_hosts: 
  infra0:            
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:  
    ip: 192.168.24.65
orchestration_hosts:                                                                                
  infra0:            
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
dashboard_hosts:
  infra0:            
    ip: 192.168.24.35
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
network_hosts:
  infra0:            
    ip: 192.168.24.35 
  infra1:
    ip: 192.168.24.69
  infra2:
    ip: 192.168.24.65
compute_hosts:
  compute0:          
    ip: 192.168.24.98
  compute1:
    ip: 192.168.24.53

storage_hosts:
 infra0:
  ip: 192.168.24.35
  container_vars:
   cinder_backends:
     limit_container_types: cinder_volume
     rbd:
       volume_group: cinder-volumes
       volume_driver: cinder.volume.drivers.rbd.RBDDriver
       volume_backend_name: rbd
       rbd_pool: volumes
       rbd_ceph_conf: /etc/ceph/ceph.conf
       rbd_user: cinder
 infra1:
  ip: 192.168.24.69
  container_vars:
   cinder_backends:
     limit_container_types: cinder_volume
     rbd:
       volume_group: cinder-volumes
       volume_driver: cinder.volume.drivers.rbd.RBDDriver
       volume_backend_name: rbd
       rbd_pool: volumes
       rbd_ceph_conf: /etc/ceph/ceph.conf
       rbd_user: cinder
 infra2:
  ip: 192.168.24.65
  container_vars:
   cinder_backends:
     limit_container_types: cinder_volume
     rbd:
       volume_group: cinder-volumes
       volume_driver: cinder.volume.drivers.rbd.RBDDriver
       volume_backend_name: rbd
       rbd_pool: volumes
       rbd_ceph_conf: /etc/ceph/ceph.conf
       rbd_user: cinder
    
